## Introduction To Tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0-rc0


#### 1 - create tensors with tf.constant()

In [2]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensaion of a tensor
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
#check the dimension of a vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([
    [10,7],
    [7,10]
])

In [7]:
# check the dimension of a matrix
matrix.ndim

2

In [10]:
# create another matrix 
another_matrix = tf.constant([
    [10.,7.],
    [8.,2.]
],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  2.]], dtype=float16)>

#### 2 - create tensors with tf.Variable()

In [11]:
# create changeable tensor
changeable_tensor = tf.Variable([[1,2,3],
                                [4,5,6]])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
# change a value in the tensor NOTE: do not use assingment
changeable_tensor[0,0].assign(5) 

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[5, 2, 3],
       [4, 5, 6]])>

In [13]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[5, 2, 3],
       [4, 5, 6]])>

#### 3 - create random tensors

In [27]:
# create random tensor
#tf.random.set_seed(42)
random = tf.random.Generator.from_seed(42) # set seed for reproducibility
##vrandom_tensor = random.normal([3,3],0,1)
random_tensor = tf.random.normal((3,3),0,1)
random_tensor  # from normal distribution

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.65648675, -0.4130517 ,  0.33997506],
       [-1.0056272 ,  0.70266235, -1.4008642 ],
       [-0.89780754, -0.34856176, -0.95890623]], dtype=float32)>

#### 4 - shuffling the order tensors

In [31]:
# shuffle a tensor 
unshuffled_tesnor = tf.constant([
    [1,2,3],
    [4,5,6]
])

tf.random.shuffle(unshuffled_tesnor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3]])>

#### 5 - other ways to make tensors

In [33]:
ones_tensor = tf.ones([3,3],tf.int32)
ones_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

In [34]:
tf.zeros((3,3,))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [39]:
# creating tensors from numpy array
import numpy as np
np_array = np.arange(1,25).reshape(8,-1)
np_array
tensor_from_numpy = tf.constant(np_array)
tensor_from_numpy

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])>

#### 6 - getting information from tensors

In [40]:
tensor = tf.random.normal((5,5))

In [41]:
# shape of the tensor
tensor.shape

TensorShape([5, 5])

In [42]:
# rank (nbr of dims)
tensor.ndim<

2

In [48]:
# size of a tensor
tf.size(tensor) == 25

<tf.Tensor: shape=(), dtype=bool, numpy=True>

#### 7 - manipulating tensors

In [54]:
tensor_1 = tf.constant([
    [1,2],
    [3,4]
])
tensor_2 = tf.constant([
    [5,6],
    [7,8]
])

In [55]:
tensor_1 + tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [56]:
tensor_1 * tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [57]:
tensor_1 / tensor_2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])>

In [58]:
tensor_1 @ tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [62]:
tf.transpose(tensor_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

#### 8 - changing  data type of a tensor

In [63]:
tensor = tf.constant([.5,.8])
tensor.dtype

tf.float32

In [65]:
# change the precision from float32 to float16
new_tensor = tf.cast(tensor,tf.float16)
new_tensor.dtype

tf.float16

#### 9 - aggregating tensors

In [86]:
tensor = tf.constant(np.random.randint(0,50,size=(10,6)),dtype=tf.float32)
tensor

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[24., 19., 14., 38., 41., 25.],
       [41., 48., 34., 31., 39., 33.],
       [ 4., 48., 14., 32., 35., 45.],
       [46.,  2.,  6.,  7., 15., 34.],
       [35., 48., 17., 16., 44., 44.],
       [20., 47., 33., 47., 49., 38.],
       [41.,  3., 14., 39., 28.,  9.],
       [ 6., 15., 23., 48.,  1., 29.],
       [13., 16.,  0., 28., 17.,  0.],
       [45., 36., 45., 34., 18., 32.]], dtype=float32)>

In [87]:
# max in rows
tf.reduce_max(tensor,axis=0)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([46., 48., 45., 48., 49., 45.], dtype=float32)>

In [88]:
# max of the whole matrix
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=49.0>

In [89]:
# mean
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=27.55>

In [90]:
# variance
tf.math.reduce_variance(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=228.08083>

In [91]:
# standard deviation
tf.math.reduce_std(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=15.102345>

In [95]:
# find the index of the max
tf.argmax(tensor)

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([3, 1, 9, 7, 5, 2], dtype=int64)>

In [96]:
# find the index of the min
tf.argmin(tensor)

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([2, 3, 8, 3, 7, 8], dtype=int64)>

In [108]:
# one hot encoding
tensor = tf.constant([1,2,3,4])

In [112]:
tf.one_hot(tensor,depth=4,on_value=1.,off_value=0.)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>